### ISSUE TITLE
What is the status of this project?

### ISSUE THREAD

**Issue by mudlee** [EsotericSoftware/kryonet#131]
@NathanSweet

**Comment by kmare** [comment]
I'd like to know the same. There haven't been commits since quite a while, so I wonder if it's "kinda" abandoned at this point or it's already too perfect :D 
Could anyone kindly suggest another library as good and as easy to use as this one?
Thank you!
btw, thank you to all developers for this awesome lib!

**Comment by NathanSweet** [comment]
I've been using it constantly in production for many years. I generally use TaggedFieldSerializer and don't use many of the features, unsafe, etc. For my usage, it works well. I have not been monitoring the project closely for some time.

**Comment by RobertZenz** [comment]
@NathanSweet I believe the question was whether you intent to work on it again at some point in the future, or not.

**Comment by NathanSweet** [comment]
@RobertZenz The project has all the intended features, which is why it has been in maintenance mode for a long time. I doubt new features will be added, but PRs can be merged and bugs fixed.

**Comment by RobertZenz** [comment]
@NathanSweet Merging the pull requests (or at least reviewing them) would be cool, yes, so that these contributions are not getting lost.

I believe it would be good to note that the project is in maintenance mode in the README, and if you want help for maintaining it, stating so in the README would also be a good idea.
