### ISSUE TITLE
IllegalArgumentException in Server selector thread Kills Server.

### ISSUE THREAD

**Issue by samthaku** [EsotericSoftware/kryonet#139]
Hi we have recently faced an issue with Kryo, we are using our own custom serialization based on SBE, plugged into Kryo.

We are trying to send the messages and have seen IllegalArgumentException occurring at line 188 in TcpConnection.java

The code at line 188 is below.

writeBuffer.position(writeBuffer.position() + lengthLength)

We need your confirmation on the following:

1.What we believe is that the buffer was full at the time when Kryo was trying to reserve 4 bytes for positon and because the buffer is already full, it is trying set position more than the size of the buffer. is this correct ?

2.We feel that there should have been a condition to check if buffer has enough capacity before setting position.
 a )Why such condition doesn't exist?
 b) are we using API in a wrong manner ?

3.Or there can be something else we are missing in our serialization. Please share your thoughts?

**Comment by vach** [comment]
Nathan lets assume we have 1 slow client, which caused our buffer to get full, while every other client is living just fine.

Kryo might execute this on Server thread itself, in which case it will get to that line, see that the buffer is full, then die with a "better exception" and all our clients will experience downtime... because of one slow client. Also although clients are smart enough to keep attempts to reconnect, but server wont restart, it will simply die...

**Comment by vach** [comment]
Or lets say we were aware enough to catch that exception, what are we supposed to do? we cant "fix" the selector thread its already out of the loop, so only option is to restart kryo server and again bother other clients.
It is easy to guard against this in Serialization instance, we simply check that we never write beyond buffer.cap - 4... but that means user must know implementation details of the selector.
Imho whatever kryoserver does, except dying is good. Like disconnect that slow client?
